### PR TITLE
ssim: Handle negative structure values with small gamma

### LINKED ISSUE #16: SSIM throws  error on γ values
The SSIM throws error on small γ values
```
img = testimage("lena_gray_256") .|> Float64
noisy_img = img .+ 0.1 .* randn(size(img))

iqi = SSIM(KernelFactors.gaussian(1.5, 11), (0.0, 0.0448, 0.0448))  
assess(iqi, img, noisy_img)

ERROR: DomainError with -0.1274347376387049:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
```

Problem is that σxy sometimes is negative and so `s` is -ve. And it throws DomainError, when taking power of -ve number.
https://github.com/JuliaImages/ImageQualityIndexes.jl/blob/c08443503e28f2bdb32620e9a4b95b71367abc0f/src/ssim.jl#L112-L114

### PR DESCRIPTION
**Pull request by jiviteshjain**
This commit prevents the structure (s) values from becoming negative if gamma is less than 1 to prevent complex number results.
Not so sure if we should always do this, or only when gamma is less than 1. In case we do the former, one of the tests fails as the value differs slightly.
Fixes #16

### CODE REVIEW

**Comment by johnnychen94** [comment]
Looks good and is an reasonable solution to me, but I prefer to have a look at other ssim implementations before we deciding to do this. Could you find some time to check this?

BTW, a test case for #16 is needed.

**Comment by jiviteshjain** [comment]
Sure, @johnnychen94 !

Should the test case be only checking that the code runs without throwing errors in this situation, or should it also compare the resultant value against some other implementation?

If the later's the case, then I'm not sure which implementation to use, because as the [comments](https://github.com/JuliaImages/ImageQualityIndexes.jl/issues/16#issuecomment-645530845) on the issue suggest, almost all of them out there restrict alpha, beta and gamma to 1.

**Comment by johnnychen94** [comment]
> Should the test case be only checking that the code runs without throwing errors in this situation, or should it also compare the resultant value against some other implementation?

I don't have strong opinion to this; I myself would record the result with a comment saying something like "this is not standard ssim implementation and the result can be different in other implementations", e.g., 

https://github.com/JuliaImages/ImageQualityIndexes.jl/blob/c08443503e28f2bdb32620e9a4b95b71367abc0f/test/ssim.jl#L46

and when the behavior changes in the future, expectedly or unexpectedly, we get a notification from test failure.

File: src/ssim.jl [hunk 1]
```diff
@@ -110,7 +110,9 @@ function _ssim_map(iqi::SSIM, x::GenericGrayImage, ref::GenericGrayImage, peakva
         l = @. (2μxy + C₁)/(μx² + μy²) # equation (6) in [1]
         c = @. (2σx_σy + C₂)/(σx² + σy² + C₂) # equation (9) in [1]
         s = @. (σxy + C₃)/(σx_σy + C₃) # equation (10) in [1]
-
+        if γ < 1.0
```
Comment (johnnychen94) [inline src/ssim.jl:116]: better to leave a comment with reference to #16 here

**Review by johnnychen94 — APPROVED** [review]

**Comment by johnnychen94** [comment]
Thanks again for all the nice research @jiviteshjain @mgautam98 ! I plan to tag the new release together with #19 

Really looking forward to your next contributions to JuliaImages.

File: src/ssim.jl [hunk 2]
```diff
@@ -111,6 +111,11 @@ function _ssim_map(iqi::SSIM, x::GenericGrayImage, ref::GenericGrayImage, peakva
         c = @. (2σx_σy + C₂)/(σx² + σy² + C₂) # equation (9) in [1]
         s = @. (σxy + C₃)/(σx_σy + C₃) # equation (10) in [1]
 
+        # ensure that negative numbers in s are not being raised to powers less
+        # than 1, non-standard implementation
+        if γ < 1.0
+            s = max.(s, zero(eltype(s)))
```
Comment (johnnychen94) [inline src/ssim.jl:117]: In Matlab R2020a, it forces a `s = abs.(s)` kind of change for all cases, including the default cases when `[α, β, γ] ≈ [1.0, 1.0, 1.0]`

FYI, here's the reply from MATLAB developers wrt the SSIM changes in R2020a:

> 1. MATLAB implemented the algo exactly like the ref paper
> 
> Refer to
> https://www.mathworks.com/help/images/ref/ssim.html
> References
> 
> 2. For some combinations of input, this results in complex valued outputs. In this context, complex valued output does not make sense.
> 
> 3. Based on our understanding of the algo, we think taking the abs value of the covariance is the right thing to do in this context.
>
> So, results in 20a is "correct". However please consider, if the complex valued output make sense for you.

I'm trying to get involved and "persuade" them that this isn't handled correctly.
